language: php

sudo: false

cache:
  directory:
      - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

install:
  - composer self-update
  - composer install --prefer-dist

script:
  - php --no-php-ini ./vendor/bin/phpunit

notifications:
  email: false
