language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

cache:
  directories:
    - $HOME/.composer

install:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist $COMPOSER_FLAGS

script:
  - php --no-php-ini ./vendor/bin/phpunit

notifications:
  email: false
