language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: CODE_COVERAGE=1

cache:
  directories:
    - $HOME/.composer/cache

install: wget -qO - https://github.com/Slamdunk/travis-scripts/raw/master/php-install.sh | sh

script: wget -qO - https://github.com/Slamdunk/travis-scripts/raw/master/php-script.sh | sh

notifications:
  email: false
