language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly

cache:
  directories:
    - $HOME/.composer

install:
  - phpenv config-rm xdebug.ini || return 0
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email: false
